projects/urls.py
from django.urls import path

from projects import views

app_name = "projects"

urlpatterns = [
    path("", views.ProjectsListView.as_view(), name="projects_list"),
    path("owned-projects/", views.ProjectsOwnedListView.as_view(),
         name="projects_owned"),
    path("review/", views.ProjectsReviewListView.as_view(),
         name="projects_review_list"),
    path("create-project/", views.ProjetCreateView.as_view(), name="project_create"),
    path("delete-project/<slug:slug>/",
         views.ProjectDeleteView.as_view(), name="project_delete"),
    path("update-project/<slug:slug>/",
         views.ProjectUpdateView.as_view(), name="project_update"),
    path("details/<slug:slug>/",
         views.ProjectDetailView.as_view(), name="project_detail"),
    path("reprove/<slug:slug>/",
         views.ReviewProjectView.as_view(), name="project_review"),

    path("withdrawal-request/create/<slug:slug>/",
         views.WithdrawalRequestCreateView.as_view(), name="withdrawal_request_create"),
    path("withdrawal-request/update/<int:pk>/",
         views.WithdrawalRequestUpdateView.as_view(), name="withdrawal_request_update"),
    path("withdrawal-request/reply/<int:pk>/",
         views.WithdrawalRequestReplyView.as_view(), name="withdrawal_request_reply"),
    path("withdrawal-requests/", views.WithdrawalRequestListView.as_view(),
         name="withdrawal_requests_list"),
    path("withdrawal-requests/staff/", views.WithdrawalRequestStaffListView.as_view(),
         name="withdrawal_requests_staff_list"),
    path("withdrawal-request/details/<int:pk>/",
         views.WithdrawalRequestDetailView.as_view(), name="withdrawal_request_detail"),

    path("project-donations/<slug:slug>", views.DonationsProjectListView.as_view(),
         name="donations_project"),
    path("owned-donations/", views.DonationsOwnedListView.as_view(),
         name="donations_owned"),
    path("donate-project/<slug:slug>/",
         views.DonateProjectView.as_view(), name="donate_project"),
    path("donation/details/<int:pk>/",
         views.DonationDetailView.as_view(), name="donation_detail"),

    path("donation/webhook/", views.webhook, name="donation_webhook"),
]

superacao_coletiva/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # Django Admin
    path("admin/", admin.site.urls),
    # User Management
    path("accounts/", include("allauth.urls")),
    # Home
    path("", TemplateView.as_view(
        template_name="global/pages/home.html"), name='home'),
    # Users
    path("users/", include("users.urls")),
    # Projects
    path("projects/", include("projects.urls")),
    # Topics
    path("topics/", include("topics.urls")),

    # 3rd party

    # TinyMCE
    path('tinymce/', include('tinymce.urls')),
    # PWA
    path('', include('pwa.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("update/",
         views.UserChange.as_view(), name="user_update"),
    path("profile/<int:pk>/",
         views.UserProfileView.as_view(), name="user_profile"),
]

projects/views/donation.py
import json
from datetime import datetime as dt

import mercadopago
import requests
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import BadRequest
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, DetailView, ListView

from projects.forms import DonateProjectForm
from projects.models import Donation, Project

DONATIONS_PAGINATE_BY = 5

# Donations and payments using Mercado Pago.

# Mercado Pago
MERCADO_PAGO_TOKEN = settings.MERCADO_PAGO_TOKEN
MERCADO_PAGO_STATUS_API = "https://api.mercadopago.com/v1/payments/{}?access_token={}"
sdk = mercadopago.SDK(MERCADO_PAGO_TOKEN)

# Webhook Mercado Pago.


@csrf_exempt
def webhook(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        payment_id = data['data']['id']

        response = requests.get(
            MERCADO_PAGO_STATUS_API.format(payment_id, MERCADO_PAGO_TOKEN)
        ).json()

        try:
            donation_id = response['additional_info']['items'][0]['id']
            donation = Donation.objects.get(id=donation_id)
            donation.payment_infos = response
            donation.save()

            if (response['status'] == 'approved'):
                donation.project.collected = donation.project.collected + donation.amount
                donation.project.save()

        except Exception as e:
            pass

        return HttpResponse('Webhook received', status=200)

    else:
        raise Http404


@method_decorator(login_required, name='dispatch')
class DonateProjectView(UserPassesTestMixin, CreateView):
    model = Donation
    form_class = DonateProjectForm
    template_name = 'projects/pages/donate_project.html'

    def test_func(self):
        project = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        return (
            project.owner != self.request.user and
            project.is_published and
            project.deadline >= dt.now().date()
        )

    def get_success_url(self) -> str:
        return reverse("projects:donation_detail", kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['project'] = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        ctx['progress'] = round(
            (100 * ctx['project'].collected) / ctx['project'].goal)
        ctx['remaining'] = ctx['project'].goal - ctx['project'].collected

        return ctx

    def get_initial(self):
        return {
            'user': self.request.user,
            'project':  get_object_or_404(
                Project,
                slug=self.kwargs['slug'],
            )
        }

    def form_valid(self, form):
        if form.cleaned_data.get('project').slug != self.kwargs['slug'] or form.cleaned_data.get('user') != self.request.user:
            raise BadRequest('Invalid request.')

        donation = form.save()

        request_merc_pago = sdk.preference().create({
            "items": [
                {
                    "id": donation.id,
                    "title": form.cleaned_data.get('project').title,
                    "quantity": 1,
                    "unit_price": form.cleaned_data.get('amount')
                }
            ]
        })["response"]

        id_checkout = request_merc_pago['id']

        donation.id_checkout = id_checkout
        donation.save()

        self.request.session['link_checkout'] = request_merc_pago['sandbox_init_point']

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class DonationDetailView(UserPassesTestMixin, DetailView):
    model = Donation
    context_object_name = 'donation'
    template_name = 'projects/pages/donation_detail.html'

    def test_func(self):
        return (
            self.request.user.is_staff or
            self.request.user == self.get_object().user or
            self.request.user == self.get_object().project.owner
        )

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        link_checkout = self.request.session.get('link_checkout')
        if link_checkout is not None:
            del self.request.session['link_checkout']

            ctx['link_checkout'] = link_checkout
        return ctx


@method_decorator(login_required, name='dispatch')
class DonationsProjectListView(UserPassesTestMixin, ListView):
    model = Donation
    context_object_name = 'donations'
    ordering = ['-created']
    template_name = 'projects/pages/donations_project_list.html'
    paginate_by = DONATIONS_PAGINATE_BY

    def test_func(self):
        project = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        return (
            self.request.user.is_staff or
            self.request.user == project.owner
        )

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            project__slug=self.kwargs.get('slug'),
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['project'] = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        return ctx


@method_decorator(login_required, name='dispatch')
class DonationsOwnedListView(ListView):
    model = Donation
    context_object_name = 'donations'
    ordering = ['-created']
    template_name = 'projects/pages/donations_owned_list.html'
    paginate_by = DONATIONS_PAGINATE_BY

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            user=self.request.user
        )
        return qs

projects/views/withdrawal_request.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import BadRequest
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView
from django_filters.views import FilterView
from projects.filters import WithdrawalRequestListFilter
from projects.forms import (WithdrawalRequestCreateForm,
                            WithdrawalRequestReplyForm,
                            WithdrawalRequestUpdateForm)
from projects.models import Project, WithdrawalRequest

WITHDRAWAL_REQUEST_PAGINATE_BY = 5

# Withdrawal requests from project owners.


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestCreateView(UserPassesTestMixin, CreateView):
    model = WithdrawalRequest
    form_class = WithdrawalRequestCreateForm
    template_name = 'projects/pages/withdrawal_request_create.html'

    def test_func(self):
        project = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        return (
            project.owner == self.request.user and
            project.is_withdrawal_available() and
            project.collected > 0 and
            not project.withdrawalrequest_set.all().count() > 0
        )

    def get_success_url(self) -> str:
        return reverse("projects:withdrawal_request_detail", kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['project'] = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )

        return ctx

    def get_initial(self):
        return {
            'user': self.request.user,
            'project': get_object_or_404(
                Project,
                slug=self.kwargs['slug'],
            ),
        }

    def form_valid(self, form):
        if form.cleaned_data.get('project').slug != self.kwargs['slug'] or form.cleaned_data.get('user') != self.request.user:
            raise BadRequest('Invalid request.')

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestUpdateView(UserPassesTestMixin, UpdateView):
    model = WithdrawalRequest
    form_class = WithdrawalRequestUpdateForm
    context_object_name = 'w_request'
    template_name = 'projects/pages/withdrawal_request_update.html'

    def test_func(self):
        return (
            self.get_object().project.owner == self.request.user
            and not self.get_object().paid
        )

    def get_success_url(self) -> str:
        return reverse("projects:withdrawal_request_detail", kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestReplyView(UserPassesTestMixin, UpdateView):
    model = WithdrawalRequest
    form_class = WithdrawalRequestReplyForm
    context_object_name = 'w_request'

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self) -> str:
        return reverse("projects:withdrawal_request_detail", kwargs={'pk': self.object.id})

    def get(self, request, pk):
        raise Http404

    def form_invalid(self, form):
        self.request.session['reply_form'] = self.request.POST
        return redirect(reverse("projects:withdrawal_request_detail", kwargs={'pk': self.get_object().id}))


class WithdrawalRequestDetailView(UserPassesTestMixin, DetailView):
    model = WithdrawalRequest
    context_object_name = 'w_request'
    template_name = 'projects/pages/withdrawal_request_detail.html'

    def test_func(self):
        return (
            self.request.user == self.get_object().user or
            self.request.user.is_staff
        )

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        if self.request.user.is_staff:
            form_data = self.request.session.get('reply_form')
            if form_data is not None:
                del self.request.session['reply_form']
                ctx['reply_form'] = WithdrawalRequestReplyForm(form_data)
            else:
                ctx['reply_form'] = WithdrawalRequestReplyForm(
                    initial={
                        'paid': self.get_object().paid,
                        'comments': self.get_object().comments,
                        'payment_proof': self.get_object().payment_proof,
                    }
                )

        return ctx


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestListView(FilterView):
    model = WithdrawalRequest
    context_object_name = 'w_requests'
    ordering = ['-created']
    template_name = 'projects/pages/withdrawal_requests_list.html'
    paginate_by = WITHDRAWAL_REQUEST_PAGINATE_BY
    filterset_class = WithdrawalRequestListFilter

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            user=self.request.user
        )
        return qs


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestStaffListView(UserPassesTestMixin, FilterView):
    model = WithdrawalRequest
    context_object_name = 'w_requests'
    ordering = ['-created']
    template_name = 'projects/pages/withdrawal_requests_list.html'
    paginate_by = WITHDRAWAL_REQUEST_PAGINATE_BY
    filterset_class = WithdrawalRequestListFilter

    def test_func(self):
        return self.request.user.is_staff

projects/templates/projects/pages/donate_project.html
{% extends 'global/base.html' %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Apoiar Projeto{% endblock %}

{% block content_title %}
    <div class="text-break text-wrap">
        <i class="bi bi-clipboard-fill text-primary me-2"></i>
        Apoiar projeto - <a href="{% url 'projects:project_detail' project.slug %}">{{project.title|truncatechars:32}}</a>
    </div>
{% endblock content_title %}

{% block content %}
    <section class="d-flex flex-column flex-lg-row">
        <div class="col-12 col-lg-6 p-0 bg-light">
            <img class="img-fluid project-img" {% include 'projects/partials/project_img_attrs.html' %} >
        </div>
        <div class="border-0 d-flex flex-column justify-content-between col-lg-6 px-4 pb-4 pb-lg-0 project-info">
            <div>
                <i class="bi bi-cash-coin me-1 text-primary fs-5"></i> 
                <b>Valor Arrecadado:</b> R$ {{ project.collected | floatformat:2 }}
            </div>
            
            <div>
                <i class="bi bi-cash me-1 text-primary fs-5"></i> 
                <b>Objetivo:</b> R$ {{ project.goal | floatformat:2}} 
            </div>
            
            <div class="d-flex flex-column flex-lg-row">
                <span>
                    <i class="bi bi-percent me-1 text-primary fs-5"></i>
                    <b>Progresso:</b>
                </span>
                <div class="progress flex-fill col-12 col-lg-auto mx-2 position-relative" style="height: 25px;">
                    <span class="text-center px-3 align-self-center position-absolute w-100 fs-6">{{progress}}%</span>
                    <div class="progress-bar bg-success" role="progressbar" style="width: {{progress | floatformat:0}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>

            {% if project.is_flexible %}
                <div>
                    <i class="bi bi-unlock me-1 text-primary fs-5"></i>
                    Campanha Flexível
                    <a class="text-decoration-none black ms-1" data-bs-toggle="tooltip" data-bs-placement="right" title="Este projeto aceita doações acima do valor definido como meta."><i class="bi bi-info-circle"></i></a> 
                </div>
            {% endif %}

            <div>
                <i class="bi bi-calendar-event me-1 text-primary fs-5"></i>
                Data de Encerramento: <b>{{ project.deadline }}</b>
            </div>

            {% if remaining > 0 %}
                <div>
                    <i class="bi bi-flag me-1 text-primary fs-5"></i>
                    Faltam <span class="fw-bold">R$ {{ remaining | floatformat:0 }}</span> para o projeto atingir a sua meta.
                </div>
            {% endif %}

            <form method="post">
                {% crispy form %}
                <button type="submit" class="btn btn-lg btn-primary mt-3 col-12">
                    <i class="bi bi-cash-coin me-1"></i> 
                    Apoiar Projeto
                </button>
            </form>
        </div>
    </section>
{% endblock %}

projects/templates/projects/pages/donation_detail.html
{% extends 'global/base.html' %}

{% block title %}Detalhes da Doação{% endblock %}

{% block content_title %}
    <div>
        <i class="bi bi-clipboard2-heart text-primary me-2"></i>
        Detalhes da Doação
    </div>
{% endblock content_title %}

{% block content %}

    {% if link_checkout %}
        <div class="alert alert-success text-center" role="alert">
            Estamos muito felizes em receber seu apoio! <br>
            Caso não a tela de pagamento não tenha sido aberta, por favor clique 
            <a id="link_checkout" href="{{link_checkout}}" class="alert-link" target="_blank" rel="noopener noreferrer">aqui</a> 
            para realizar o pagamento.
        </div>
    {% endif %}

    <ul class="list-group">
        <li class="list-group-item d-flex gap-2 py-3">
            <strong class="col">
                <i class="bi bi-clipboard text-primary me-1"></i>
                Doado para o projeto:
            </strong>
            <span class="col">
                <a class="decrease-opacity-hover underline-hover text-decoration-none" href="{% url 'projects:project_detail' donation.project.slug %}">
                    {{ donation.project.title|truncatechars:32 }}
                </a>
            </span>
        </li>
        <li class="list-group-item d-flex gap-2 py-3">
            {% include 'users/partials/user_link.html' with user_link_user=donation.user user_link_label_wrapper_class='col' user_link_icon_class='text-primary' user_link_separator='Usuário: ' user_link_username_wrapper_class='col ms-1' user_link_username_class='link-primary' %}
        </li>
        <li class="list-group-item d-flex gap-2  py-3">
            <strong class="col">
                <i class="bi bi-calendar-event text-primary me-1"></i>
                Data/Hora da doação:
            </strong>
            <span class="col">
                {{ donation.created }}
            </span>
        </li>
        <li class="list-group-item d-flex gap-2 py-3">
            <strong class="col">
                <i class="bi bi-calendar-event text-primary me-1"></i>
                Data/Hora da última atualização:
            </strong>
            <span class="col">
                {{ donation.modified }}
            </span>
        </li>
        <li class="list-group-item d-flex gap-2 py-3">
            <strong class="col">
                <i class="bi bi-cash-coin text-primary me-1"></i>
                Valor:
            </strong>
            <span class="col">
                R$ {{ donation.amount|floatformat:2 }}
            </span>
        </li>
        <li class="list-group-item d-flex align-items-center gap-2 py-3">
            <strong class="col">
                {% if donation.payment_infos.status == 'approved' %}
                    <i class="bi bi-check-circle-fill me-1 text-primary" data-bs-toggle="tooltip" data-bs-placement="right" title="Pagamento Aprovado"></i>
                {% elif donation.payment_infos.status == 'rejected' %}
                    <i class="bi bi-x-circle-fill me-1 text-danger" data-bs-toggle="tooltip" data-bs-placement="right" title="Pagamento Rejeitado"></i>
                {% else %}
                    <i class="bi bi-check-circle me-1" data-bs-toggle="tooltip" data-bs-placement="right" title="Pagamento Pendente"></i>
                {% endif %}
                Status do pagamento:
            </strong>
            <span class="col d-flex flex-wrap gap-2 justify-content-between align-items-center">
                {% if donation.payment_infos.status == 'approved' %}
                    Pagamento Aprovado
                {% elif donation.payment_infos.status == 'rejected' %}
                    Pagamento Rejeitado
                {% else %}
                    Pagamento Pendente
                {% endif %}
            </span>
        </li>
    </ul>

    {% if link_checkout %}
        <script defer>
            document.getElementById('link_checkout').click();
        </script>
    {% endif %}

{% endblock %}

projects/templates/projects/pages/donations_owned_list.html
{% extends 'global/base.html' %}

{% block title %}Histórico de Doações{% endblock %}

{% block content_title %}
    <div>
        <i class="bi bi-clock-history text-primary me-2"></i>
        Histórico de Doações
    </div>
{% endblock content_title %}

{% block content %}
    <section>
        {% include 'projects/partials/donations_list.html' %}
    </section>
{% endblock %}

projects/templates/projects/pages/donations_project_list.html
{% extends 'global/base.html' %}

{% block title %}Doações do Projeto{% endblock %}

{% block content_title %}
    <div>
        <i class="bi bi-clipboard-fill text-primary me-2"></i>
        Doações do projeto - <a href="{% url 'projects:project_detail' project.slug %}">{{project.title}}</a>
    </div>
{% endblock content_title %}

{% block content %}
    <section>
        {% include 'projects/partials/donations_list.html' %}
    </section>
{% endblock %}

projects/templates/projects/pages/project_reprove.html
{% extends 'global/base.html' %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Reprovar Projeto{% endblock %}

{% block content_title %}
    <div class="text-break text-wrap">
        <i class="bi bi-clipboard-fill text-primary me-2"></i>
        Reprovar Projeto - <a href="{% url 'projects:project_detail' project.slug %}">{{project.title|truncatechars:32}}</a>
    </div>
{% endblock content_title %}

{% block content %}
    <form method="post">
        {% crispy form %}
        <button type="submit" class="btn btn-lg btn-danger mt-3 col-12">
            {% if not project.is_reproved %}
                <i class="bi bi-x-lg me-1"></i>
                Reprovar Projeto
            {% else %}
                <i class="bi bi-pencil-square me-1"></i>
                Salvar Alterarações
            {% endif %}
        </button>
    </form>
{% endblock %}

projects/templates/projects/pages/withdrawal_request_detail.html
{% extends 'global/base.html' %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Solicitação de Saque{% endblock %}

{% block content_title %}
    <div>
        <i class="bi bi-coin text-primary me-2"></i>
        Detalhes da Solicitação de Saque
    </div>
{% endblock content_title %}

{% block content %}

    <div class="d-flex gap-5 flex-wrap">
        <section class="col">
            {% if w_request.comments %}
                <div class="card w-100 mb-3">
                    <header class="card-header bg-danger text-light d-flex flex-wrap justify-content-between align-items-center">
                        <h3 class="fs-4 d-flex col-12 col-lg-auto justify-content-center justify-content-lg-start">
                            <i class="bi bi-exclamation-triangle-fill me-3"></i>
                            Atenção 
                        </h3>
                    </header>
                    <div class="card-body">
                        <div class="fw-bold mb-2 d-flex flex-nowrap">
                            <i class="bi bi-chat-right-quote me-2 text-danger"></i>
                            A nossa equipe deixou um comentário: 
                        </div>
                        <hr>
                        <p class="card-text text-justify">
                            {{ w_request.comments|safe }}
                        </p>
                    </div>
                </div>
            {% endif %}

            <ul class="list-group">
                <li class="list-group-item d-flex gap-2 py-3">
                    <strong class="col">
                        <i class="bi bi-clipboard text-primary me-1"></i>
                        Referente ao projeto:
                    </strong>
                    <span class="col">
                        <a class="decrease-opacity-hover underline-hover text-decoration-none" href="{% url 'projects:project_detail' w_request.project.slug %}">
                            {{ w_request.project.title|truncatechars:32 }}
                        </a>
                    </span>
                </li>
                <li class="list-group-item d-flex gap-2 py-3">
                    {% include 'users/partials/user_link.html' with user_link_user=w_request.user user_link_label_wrapper_class='col' user_link_icon_class='text-primary' user_link_separator='Solicitado por: ' user_link_username_wrapper_class='col ms-1' user_link_username_class='link-primary' %}
                </li>
                <li class="list-group-item d-flex gap-2  py-3">
                    <strong class="col">
                        <i class="bi bi-calendar-event text-primary me-1"></i>
                        Data/Hora da solicitação:
                    </strong>
                    <span class="col">
                        {{ w_request.created }}
                    </span>
                </li>
                <li class="list-group-item d-flex gap-2 py-3">
                    <strong class="col">
                        <i class="bi bi-calendar-event text-primary me-1"></i>
                        Data/Hora da última atualização:
                    </strong>
                    <span class="col">
                        {{ w_request.modified }}
                    </span>
                </li>
                <li class="list-group-item d-flex gap-2 py-3">
                    <strong class="col">
                        <i class="bi bi-cash-coin text-primary me-1"></i>
                        Valor:
                    </strong>
                    <span class="col">
                        R$ {{ w_request.project.collected|floatformat:2 }}
                    </span>
                </li>
                <li class="list-group-item d-flex align-items-center gap-2 py-3">
                    <strong class="col">
                        {% if w_request.paid %}
                            <i class="bi bi-check-circle-fill text-primary me-1" data-bs-toggle="tooltip" data-bs-placement="right" title="Transferência Realizada."></i>
                        {% else %}
                            <i class="bi bi-check-circle me-1" data-bs-toggle="tooltip" data-bs-placement="right" title="Transferência Pendente"></i>
                        {% endif %}
                        Status:
                    </strong>
                    <span class="col d-flex flex-wrap gap-2 justify-content-between align-items-center">
                        {% if w_request.paid %}
                            Pagamento Concluído
                            <a class="btn btn-sm btn-primary" href="{{ w_request.payment_proof.url }}" target="_blank" rel="noopener noreferrer">
                                <i class="bi bi-download me-1"></i>
                                Baixar Comprovante
                            </a>
                        {% else %}
                            Pendente
                        {% endif %}
                    </span>
                </li>
                <li class="list-group-item d-flex flex-wrap gap-1 py-3">
                    <div class="col-12 d-flex justify-content-start align-items-center">
                        <strong class="col">
                            <i class="bi bi-cash-coin text-primary me-1"></i>
                            Informações do Beneficiário:
                        </strong>
                        {% if w_request.user == user %}
                            <div class="col">
                                <a href="{% url 'projects:withdrawal_request_update' w_request.id %}" class="btn btn-sm btn-warning text-light px-3">
                                    <i class="bi bi-pencil-square me-1"></i>
                                    Editar
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <hr class="col-12">
                    <span class="col-12 px-3">
                        {{ w_request.beneficiary_information|safe }}
                    </span>
                </li>
            </ul>
        </section>

        {% if reply_form %}
        
            <div class="border-end align-self-stretch d-none d-lg-inline"></div>
            
            <section class="col-12 col-lg-5">
                <header>
                    <h3>
                        Atualizar Status
                    </h3>
                </header>

                <hr class="my-3">

                <form action="{% url 'projects:withdrawal_request_reply' w_request.id %}" method="post" enctype="multipart/form-data">
                    {% crispy reply_form %}

                    <button type="submit" class="btn btn-lg btn-primary mt-3 col-12">
                        <i class="bi bi-pencil-square me-1"></i>
                        Salvar
                    </button>
                </form>
            </section>
        {% endif %}
    </div>
{% endblock %}