projects/urls.py
from django.urls import path

from projects import views

app_name = "projects"

urlpatterns = [
    path("", views.ProjectsListView.as_view(), name="projects_list"),
    path("owned-projects/", views.ProjectsOwnedListView.as_view(),
         name="projects_owned"),
    path("review/", views.ProjectsReviewListView.as_view(),
         name="projects_review_list"),
    path("create-project/", views.ProjetCreateView.as_view(), name="project_create"),
    path("delete-project/<slug:slug>/",
         views.ProjectDeleteView.as_view(), name="project_delete"),
    path("update-project/<slug:slug>/",
         views.ProjectUpdateView.as_view(), name="project_update"),
    path("details/<slug:slug>/",
         views.ProjectDetailView.as_view(), name="project_detail"),
    path("reprove/<slug:slug>/",
         views.ReviewProjectView.as_view(), name="project_review"),

    path("withdrawal-request/create/<slug:slug>/",
         views.WithdrawalRequestCreateView.as_view(), name="withdrawal_request_create"),
    path("withdrawal-request/update/<int:pk>/",
         views.WithdrawalRequestUpdateView.as_view(), name="withdrawal_request_update"),
    path("withdrawal-request/reply/<int:pk>/",
         views.WithdrawalRequestReplyView.as_view(), name="withdrawal_request_reply"),
    path("withdrawal-requests/", views.WithdrawalRequestListView.as_view(),
         name="withdrawal_requests_list"),
    path("withdrawal-requests/staff/", views.WithdrawalRequestStaffListView.as_view(),
         name="withdrawal_requests_staff_list"),
    path("withdrawal-request/details/<int:pk>/",
         views.WithdrawalRequestDetailView.as_view(), name="withdrawal_request_detail"),

    path("project-donations/<slug:slug>", views.DonationsProjectListView.as_view(),
         name="donations_project"),
    path("owned-donations/", views.DonationsOwnedListView.as_view(),
         name="donations_owned"),
    path("donate-project/<slug:slug>/",
         views.DonateProjectView.as_view(), name="donate_project"),
    path("donation/details/<int:pk>/",
         views.DonationDetailView.as_view(), name="donation_detail"),

    path("donation/webhook/", views.webhook, name="donation_webhook"),
]

superacao_coletiva/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # Django Admin
    path("admin/", admin.site.urls),
    # User Management
    path("accounts/", include("allauth.urls")),
    # Home
    path("", TemplateView.as_view(
        template_name="global/pages/home.html"), name='home'),
    # Users
    path("users/", include("users.urls")),
    # Projects
    path("projects/", include("projects.urls")),
    # Topics
    path("topics/", include("topics.urls")),

    # 3rd party

    # TinyMCE
    path('tinymce/', include('tinymce.urls')),
    # PWA
    path('', include('pwa.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("update/",
         views.UserChange.as_view(), name="user_update"),
    path("profile/<int:pk>/",
         views.UserProfileView.as_view(), name="user_profile"),
]

templates/global/partials/footer.html
{% load static %}

<footer>
    <section class="bg-primary py-5 text-light">
        <div class="my-container d-flex align-items-start flex-wrap">
            <section class="col-12 col-lg-6 text-center text-lg-start">
                <header class="fw-bold fs-5 mb-4">
                    Projeto SuperAção Coletiva
                </header>
                <div class="d-grid gap-4">
                    <div class="fw-italic">
                        Mover-Se na Web - Articulação Pró-Brumadinho
                    </div>
                    <div>
                        Copyright © 2021-2022
                    </div>
                </div>
            </section>

            <section class="col-12 col-lg-3 text-center text-center text-lg-start mt-5 mt-lg-0">
                <header class="fw-bold fs-5 mb-2">
                    Plataforma
                </header>
                <div class="d-grid gap-1">
                    <div>
                        <a href="{% url 'home' %}" class="text-decoration-none text-light">Apresentação</a>
                    </div>
                    <div>
                        <a href="{% url 'projects:projects_list' %}" class="text-decoration-none text-light">Projetos</a>
                    </div>
                    {% if not user.is_authenticated %}
                        <div>
                            <a href="{% url 'account_login' %}" class="text-decoration-none text-light">Login</a>
                        </div>
                        <div>
                            <a href="{% url 'account_signup' %}" class="text-decoration-none text-light">Cadastro</a>
                        </div>
                    {% else %}
                        <div>
                            <a href="{% url 'account_logout' %}" class="text-decoration-none text-light">Sair</a>
                        </div>
                    {% endif %}
                </div>
            </section>

            <section class="col-12 col-lg-3 text-center text-lg-start mt-5 mt-lg-0">
                <header class="fw-bold fs-5 mb-2">
                    Projeto
                </header>
                <div class="d-grid gap-1">
                    <div>
                        <a href="#" class="text-decoration-none text-light">GitHub</a>
                    </div>
                    <div>
                        <a href="#" class="text-decoration-none text-light">Contato</a>
                    </div>
                </div>
            </section>
        </div>
    </section>
    <section class="my-container my-5">
        <header class="text-center fs-3">
            Apoio e desenvolvimento:
        </header>
        <div class="d-flex justify-content-around align-items-center my-5 flex-lg-row flex-column">
            <img class="img-fluid col-12 col-lg-4" src="{% static 'global/img/if-sudeste-barbacena.png' %}" alt="Logo do Instituto Federal Sudeste de Minas Gerais - Campus Barbacena">
            <img class="img-fluid col-12 col-lg-4 mt-5 mt-lg-0" src="{% static 'global/img/cwebbr-nicbr-cgibr.png' %}" alt="Logos do cweb.br, nic.br e cgi.br">
        </div>
    </section>
</footer>

templates/global/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'global/css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<link rel="stylesheet" type="text/css" href="{% static 'global/css/custom-bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'global/css/style.css' %}">

templates/global/partials/header.html
{% load static %}

<header class="bg-white shadow">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="my-container container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler"
                aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand my-1 mx-auto mx-lg-0" href="{% url 'projects:projects_list' %}">
                <img src="{% static 'global/img/brand.png' %}" height="75" alt="SuperAção Coletiva">
            </a>
            <div class="collapse navbar-collapse justify-content-end" id="navbarToggler">
                <ul class="navbar-nav text-center gap-2">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'projects:projects_list' %}">
                            <i class="bi bi-clipboard-heart me-2"></i>
                            Apoiar Projetos
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'projects:project_create' %}">
                                <i class="bi bi-clipboard-plus me-2"></i>
                                Criar Projeto
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'projects:projects_owned' %}">
                                <i class="bi bi-list-ul me-2"></i>
                                Meus Projetos
                            </a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userNavbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-person-lock me-2"></i>
                                Gerenciar
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userNavbarDropdownMenuLink">
                                {% if user.is_superuser  %}
                                    <li class="dropdown-item">
                                        <a class="nav-link" href="{% url 'admin:index' %}">
                                            <i class="bi bi-person-gear me-2"></i>
                                            Página de Administração
                                        </a>
                                    </li>

                                    <li><hr class="dropdown-divider"></li>    
                                {% endif %}

                                <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'projects:projects_review_list' %}">
                                        <i class="bi bi-clipboard-pulse me-2"></i>
                                        Revisar Projetos
                                    </a>
                                </li>
                                <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'projects:withdrawal_requests_staff_list' %}">
                                        <i class="bi bi-coin me-2"></i>
                                        Solicitações de Saque
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userNavbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.profile_picture %}
                                    <img class="small-user-pic me-2" src="{{ user.profile_picture.url }}"
                                        alt="Imagem de perfil do usuário {{ user.username }}">
                                {% else %}
                                    <i class="bi bi-person me-2"></i>
                                {% endif %}
                                {{user.username|truncatechars:16}}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userNavbarDropdownMenuLink">
                                <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'projects:donations_owned' %}">
                                        <i class="bi bi-clock-history me-2"></i>
                                        Histórico de Doações
                                    </a>
                                </li>
                                <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'projects:withdrawal_requests_list' %}">
                                        <i class="bi bi-coin me-2"></i>
                                        Solicitações de Saque
                                    </a>
                                </li>

                                <li><hr class="dropdown-divider"></li>

                                <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'users:user_update' %}">
                                        <i class="bi bi-gear me-2"></i>
                                        Alterar Dados
                                    </a>
                                </li>
                                <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'users:user_profile' user.id %}">
                                        <i class="bi bi-person-square me-2"></i>
                                        Ver Perfil
                                    </a>
                                </li>
                                <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'account_logout' %}?next={{ request.path }}">
                                        <i class="bi bi-box-arrow-right me-2 text-danger"></i>
                                        Sair
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">
                                <i class="bi bi-box-arrow-in-right me-2"></i>
                                Entrar
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">
                                <i class="bi bi-person-plus-fill me-2"></i>
                                Cadastro
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/global/partials/messages.html
{% if messages %}
    <div class="text-center d-grid gap-2 w-100">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show text-break text-wrap" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/global/partials/pagination.html
{% if is_paginated %}
    
        <nav class="d-flex justify-content-center align-items-center">
            <ul class="pagination m-0">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% comment %}
                    {% endcomment %}?{% comment %}
                    {% endcomment %}{% if request.GET.urlencode %}{% comment %}
                        {% endcomment %}{% for key, value in request.GET.items %}{% comment %}
                            {% endcomment %}{% if key != 'page' %}{% comment %}
                                {% endcomment %}{{ key }}={{ value }}&{% comment %}
                            {% endcomment %}{% endif %}{% comment %}
                        {% endcomment %}{% endfor %}{% comment %}
                    {% endcomment %}{% endif %}{% comment %}
                    {% endcomment %}page={{page_obj.previous_page_number}}{% comment %}
                    {% endcomment %}{% if list_link %}{% comment %}
                        {% endcomment %}#{{ list_link }}{% comment %}
                    {% endcomment %}{% endif %}{% comment %}
                {% endcomment %}">&laquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&laquo;</a>
                </li>
            {% endif %} 
            {% for i in paginator.page_range %} 
                {% if page_obj.number == i %}
                    <li class="page-item active" aria-current="page"><a class="page-link">{{ i }}</a></li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{% comment %}
                            {% endcomment %}?{% comment %}
                            {% endcomment %}{% if request.GET.urlencode %}{% comment %}
                                {% endcomment %}{% for key, value in request.GET.items %}{% comment %}
                                    {% endcomment %}{% if key != 'page' %}{% comment %}
                                        {% endcomment %}{{ key }}={{ value }}&{% comment %}
                                    {% endcomment %}{% endif %}{% comment %}
                                {% endcomment %}{% endfor %}{% comment %}
                            {% endcomment %}{% endif %}{% comment %}
                            {% endcomment %}page={{ i }}{% comment %}
                            {% endcomment %}{% if list_link %}{% comment %}
                                {% endcomment %}#{{ list_link }}{% comment %}
                            {% endcomment %}{% endif %}{% comment %}
                        {% endcomment %}">{{ i }}</a>
                    </li>
                {% endif %} 
            {% endfor %} 
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="{% comment %}
                        {% endcomment %}?{% comment %}
                        {% endcomment %}{% if request.GET.urlencode %}{% comment %}
                            {% endcomment %}{% for key, value in request.GET.items %}{% comment %}
                                {% endcomment %}{% if key != 'page' %}{% comment %}
                                    {% endcomment %}{{ key }}={{ value }}&{% comment %}
                                {% endcomment %}{% endif %}{% comment %}
                            {% endcomment %}{% endfor %}{% comment %}
                        {% endcomment %}{% endif %}{% comment %}
                        {% endcomment %}page={{page_obj.next_page_number}}{% comment %}
                        {% endcomment %}{% if list_link %}{% comment %}
                            {% endcomment %}#{{ list_link }}{% comment %}
                        {% endcomment %}{% endif %}{% comment %}
                    {% endcomment %}" class="page-link">&raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&raquo;</a>
                </li>
            {% endif %}
            </ul>
        </nav>
{% endif %}

templates/global/partials/scripts.html
{% load static %}

<div vw class="enabled">
    <div vw-access-button class="active"></div>
    <div vw-plugin-wrapper>
    <div class="vw-plugin-top-wrapper"></div>
    </div>
</div>

<script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
<script>
    new window.VLibras.Widget('https://vlibras.gov.br/app');
</script>

<script src="{% static 'global/js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'global/js/jquery.mask.min.js' %}"></script>
<script src="{% static 'global/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'global/js/script.js' %}"></script>