projects/urls.py
from django.urls import path

from projects import views

app_name = "projects"

urlpatterns = [
    path("", views.ProjectsListView.as_view(), name="projects_list"),
    path("owned-projects/", views.ProjectsOwnedListView.as_view(),
         name="projects_owned"),
    path("review/", views.ProjectsReviewListView.as_view(),
         name="projects_review_list"),
    path("create-project/", views.ProjetCreateView.as_view(), name="project_create"),
    path("delete-project/<slug:slug>/",
         views.ProjectDeleteView.as_view(), name="project_delete"),
    path("update-project/<slug:slug>/",
         views.ProjectUpdateView.as_view(), name="project_update"),
    path("details/<slug:slug>/",
         views.ProjectDetailView.as_view(), name="project_detail"),
    path("reprove/<slug:slug>/",
         views.ReviewProjectView.as_view(), name="project_review"),

    path("withdrawal-request/create/<slug:slug>/",
         views.WithdrawalRequestCreateView.as_view(), name="withdrawal_request_create"),
    path("withdrawal-request/update/<int:pk>/",
         views.WithdrawalRequestUpdateView.as_view(), name="withdrawal_request_update"),
    path("withdrawal-request/reply/<int:pk>/",
         views.WithdrawalRequestReplyView.as_view(), name="withdrawal_request_reply"),
    path("withdrawal-requests/", views.WithdrawalRequestListView.as_view(),
         name="withdrawal_requests_list"),
    path("withdrawal-requests/staff/", views.WithdrawalRequestStaffListView.as_view(),
         name="withdrawal_requests_staff_list"),
    path("withdrawal-request/details/<int:pk>/",
         views.WithdrawalRequestDetailView.as_view(), name="withdrawal_request_detail"),

    path("project-donations/<slug:slug>", views.DonationsProjectListView.as_view(),
         name="donations_project"),
    path("owned-donations/", views.DonationsOwnedListView.as_view(),
         name="donations_owned"),
    path("donate-project/<slug:slug>/",
         views.DonateProjectView.as_view(), name="donate_project"),
    path("donation/details/<int:pk>/",
         views.DonationDetailView.as_view(), name="donation_detail"),

    path("donation/webhook/", views.webhook, name="donation_webhook"),
]

superacao_coletiva/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # Django Admin
    path("admin/", admin.site.urls),
    # User Management
    path("accounts/", include("allauth.urls")),
    # Home
    path("", TemplateView.as_view(
        template_name="global/pages/home.html"), name='home'),
    # Users
    path("users/", include("users.urls")),
    # Projects
    path("projects/", include("projects.urls")),
    # Topics
    path("topics/", include("topics.urls")),

    # 3rd party

    # TinyMCE
    path('tinymce/', include('tinymce.urls')),
    # PWA
    path('', include('pwa.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("update/",
         views.UserChange.as_view(), name="user_update"),
    path("profile/<int:pk>/",
         views.UserProfileView.as_view(), name="user_profile"),
]

topics/models.py
from django.conf import settings
from django.db import models
from model_utils.models import TimeStampedModel

from projects.models import Project


class Topic(TimeStampedModel, models.Model):
    user = models.ForeignKey(
        verbose_name="Criador",
        to=settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )
    project = models.ForeignKey(
        verbose_name="Projeto",
        to=Project,
        on_delete=models.SET_NULL,
        null=True

    )

    title = models.CharField(verbose_name="Título", max_length=255)
    description = models.TextField(verbose_name="Descrição")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Tópico"
        verbose_name_plural = "Tópicos"


class Message(TimeStampedModel, models.Model):
    user = models.ForeignKey(
        verbose_name="Criador",
        to=settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )
    topic = models.ForeignKey(
        verbose_name="Tópico",
        to=Topic,
        on_delete=models.CASCADE
    )

    content = models.TextField(verbose_name="Conteúdo")

    def __str__(self):
        return (self.content[:75] + '...') if len(self.content) > 75 else self.content

    class Meta:
        verbose_name = "Mensagem"
        verbose_name_plural = "Mensagens"


class MessageVote(TimeStampedModel, models.Model):
    user = models.ForeignKey(
        verbose_name="Usuário",
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    message = models.ForeignKey(
        verbose_name="Mensagem",
        to=Message,
        on_delete=models.CASCADE
    )

    value = models.BooleanField(
        verbose_name="Gostou", default=True)

    class Meta:
        verbose_name = "Voto Mensagem"
        verbose_name_plural = "Votos Mensagens"

projects/views/donation.py
import json
from datetime import datetime as dt

import mercadopago
import requests
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import BadRequest
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, DetailView, ListView

from projects.forms import DonateProjectForm
from projects.models import Donation, Project

DONATIONS_PAGINATE_BY = 5

# Donations and payments using Mercado Pago.

# Mercado Pago
MERCADO_PAGO_TOKEN = settings.MERCADO_PAGO_TOKEN
MERCADO_PAGO_STATUS_API = "https://api.mercadopago.com/v1/payments/{}?access_token={}"
sdk = mercadopago.SDK(MERCADO_PAGO_TOKEN)

# Webhook Mercado Pago.


@csrf_exempt
def webhook(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        payment_id = data['data']['id']

        response = requests.get(
            MERCADO_PAGO_STATUS_API.format(payment_id, MERCADO_PAGO_TOKEN)
        ).json()

        try:
            donation_id = response['additional_info']['items'][0]['id']
            donation = Donation.objects.get(id=donation_id)
            donation.payment_infos = response
            donation.save()

            if (response['status'] == 'approved'):
                donation.project.collected = donation.project.collected + donation.amount
                donation.project.save()

        except Exception as e:
            pass

        return HttpResponse('Webhook received', status=200)

    else:
        raise Http404


@method_decorator(login_required, name='dispatch')
class DonateProjectView(UserPassesTestMixin, CreateView):
    model = Donation
    form_class = DonateProjectForm
    template_name = 'projects/pages/donate_project.html'

    def test_func(self):
        project = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        return (
            project.owner != self.request.user and
            project.is_published and
            project.deadline >= dt.now().date()
        )

    def get_success_url(self) -> str:
        return reverse("projects:donation_detail", kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['project'] = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        ctx['progress'] = round(
            (100 * ctx['project'].collected) / ctx['project'].goal)
        ctx['remaining'] = ctx['project'].goal - ctx['project'].collected

        return ctx

    def get_initial(self):
        return {
            'user': self.request.user,
            'project':  get_object_or_404(
                Project,
                slug=self.kwargs['slug'],
            )
        }

    def form_valid(self, form):
        if form.cleaned_data.get('project').slug != self.kwargs['slug'] or form.cleaned_data.get('user') != self.request.user:
            raise BadRequest('Invalid request.')

        donation = form.save()

        request_merc_pago = sdk.preference().create({
            "items": [
                {
                    "id": donation.id,
                    "title": form.cleaned_data.get('project').title,
                    "quantity": 1,
                    "unit_price": form.cleaned_data.get('amount')
                }
            ]
        })["response"]

        id_checkout = request_merc_pago['id']

        donation.id_checkout = id_checkout
        donation.save()

        self.request.session['link_checkout'] = request_merc_pago['sandbox_init_point']

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class DonationDetailView(UserPassesTestMixin, DetailView):
    model = Donation
    context_object_name = 'donation'
    template_name = 'projects/pages/donation_detail.html'

    def test_func(self):
        return (
            self.request.user.is_staff or
            self.request.user == self.get_object().user or
            self.request.user == self.get_object().project.owner
        )

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        link_checkout = self.request.session.get('link_checkout')
        if link_checkout is not None:
            del self.request.session['link_checkout']

            ctx['link_checkout'] = link_checkout
        return ctx


@method_decorator(login_required, name='dispatch')
class DonationsProjectListView(UserPassesTestMixin, ListView):
    model = Donation
    context_object_name = 'donations'
    ordering = ['-created']
    template_name = 'projects/pages/donations_project_list.html'
    paginate_by = DONATIONS_PAGINATE_BY

    def test_func(self):
        project = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        return (
            self.request.user.is_staff or
            self.request.user == project.owner
        )

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            project__slug=self.kwargs.get('slug'),
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['project'] = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        return ctx


@method_decorator(login_required, name='dispatch')
class DonationsOwnedListView(ListView):
    model = Donation
    context_object_name = 'donations'
    ordering = ['-created']
    template_name = 'projects/pages/donations_owned_list.html'
    paginate_by = DONATIONS_PAGINATE_BY

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            user=self.request.user
        )
        return qs

projects/views/withdrawal_request.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import BadRequest
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView
from django_filters.views import FilterView
from projects.filters import WithdrawalRequestListFilter
from projects.forms import (WithdrawalRequestCreateForm,
                            WithdrawalRequestReplyForm,
                            WithdrawalRequestUpdateForm)
from projects.models import Project, WithdrawalRequest

WITHDRAWAL_REQUEST_PAGINATE_BY = 5

# Withdrawal requests from project owners.


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestCreateView(UserPassesTestMixin, CreateView):
    model = WithdrawalRequest
    form_class = WithdrawalRequestCreateForm
    template_name = 'projects/pages/withdrawal_request_create.html'

    def test_func(self):
        project = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )
        return (
            project.owner == self.request.user and
            project.is_withdrawal_available() and
            project.collected > 0 and
            not project.withdrawalrequest_set.all().count() > 0
        )

    def get_success_url(self) -> str:
        return reverse("projects:withdrawal_request_detail", kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['project'] = get_object_or_404(
            Project,
            slug=self.kwargs['slug'],
        )

        return ctx

    def get_initial(self):
        return {
            'user': self.request.user,
            'project': get_object_or_404(
                Project,
                slug=self.kwargs['slug'],
            ),
        }

    def form_valid(self, form):
        if form.cleaned_data.get('project').slug != self.kwargs['slug'] or form.cleaned_data.get('user') != self.request.user:
            raise BadRequest('Invalid request.')

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestUpdateView(UserPassesTestMixin, UpdateView):
    model = WithdrawalRequest
    form_class = WithdrawalRequestUpdateForm
    context_object_name = 'w_request'
    template_name = 'projects/pages/withdrawal_request_update.html'

    def test_func(self):
        return (
            self.get_object().project.owner == self.request.user
            and not self.get_object().paid
        )

    def get_success_url(self) -> str:
        return reverse("projects:withdrawal_request_detail", kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestReplyView(UserPassesTestMixin, UpdateView):
    model = WithdrawalRequest
    form_class = WithdrawalRequestReplyForm
    context_object_name = 'w_request'

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self) -> str:
        return reverse("projects:withdrawal_request_detail", kwargs={'pk': self.object.id})

    def get(self, request, pk):
        raise Http404

    def form_invalid(self, form):
        self.request.session['reply_form'] = self.request.POST
        return redirect(reverse("projects:withdrawal_request_detail", kwargs={'pk': self.get_object().id}))


class WithdrawalRequestDetailView(UserPassesTestMixin, DetailView):
    model = WithdrawalRequest
    context_object_name = 'w_request'
    template_name = 'projects/pages/withdrawal_request_detail.html'

    def test_func(self):
        return (
            self.request.user == self.get_object().user or
            self.request.user.is_staff
        )

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        if self.request.user.is_staff:
            form_data = self.request.session.get('reply_form')
            if form_data is not None:
                del self.request.session['reply_form']
                ctx['reply_form'] = WithdrawalRequestReplyForm(form_data)
            else:
                ctx['reply_form'] = WithdrawalRequestReplyForm(
                    initial={
                        'paid': self.get_object().paid,
                        'comments': self.get_object().comments,
                        'payment_proof': self.get_object().payment_proof,
                    }
                )

        return ctx


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestListView(FilterView):
    model = WithdrawalRequest
    context_object_name = 'w_requests'
    ordering = ['-created']
    template_name = 'projects/pages/withdrawal_requests_list.html'
    paginate_by = WITHDRAWAL_REQUEST_PAGINATE_BY
    filterset_class = WithdrawalRequestListFilter

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            user=self.request.user
        )
        return qs


@method_decorator(login_required, name='dispatch')
class WithdrawalRequestStaffListView(UserPassesTestMixin, FilterView):
    model = WithdrawalRequest
    context_object_name = 'w_requests'
    ordering = ['-created']
    template_name = 'projects/pages/withdrawal_requests_list.html'
    paginate_by = WITHDRAWAL_REQUEST_PAGINATE_BY
    filterset_class = WithdrawalRequestListFilter

    def test_func(self):
        return self.request.user.is_staff

projects/templates/projects/partials/donation_preview.html
<article class="card m-0 project-preview">
    <div class="card-body px-3 m-0 d-flex flex-row justify-content-between flex-wrap align-items-center">
        <div  class="col-auto">
            <strong>
                <i class="bi bi-calendar-event text-primary me-1"></i>
                Data/Hora:
            </strong> 
            {{ donation.created }}
        </div>

        <hr class="col-12 d-lg-none">

        <div class="col-auto">
            {% if project %}
                <div class="d-flex align-items-center">
                    {% include 'users/partials/user_link.html' with user_link_user=donation.user user_link_icon_class='text-primary' user_link_separator='Usuário: ' user_link_username_class='text-reset' %}
                </div>
            {% else %}
                <strong>
                    <i class="bi bi-clipboard text-primary me-1"></i>
                    Projeto: 
                </strong>
                <a href="{% url 'projects:project_detail' donation.project.slug %}">
                    {{ donation.project.title|truncatechars:16 }}
                </a>
            {% endif %}
        </div>

        <hr class="col-12 d-lg-none">

        <div class="col-auto text-start text-lg-center">
            <strong>
                <i class="bi bi-cash-coin text-primary me-1"></i>
                Valor:
            </strong> 
            R$ {{ donation.amount|floatformat:2 }}
        </div>

        <div class="col-auto">
            {% if donation.payment_infos.status == 'approved' %}
                <i class="bi bi-check-circle-fill text-primary" data-bs-toggle="tooltip" data-bs-placement="right" title="Pagamento Aprovado"></i>
            {% elif donation.payment_infos.status == 'rejected' %}
                <i class="bi bi-x-circle-fill text-danger" data-bs-toggle="tooltip" data-bs-placement="right" title="Pagamento Rejeitado"></i>
            {% else %}
                <i class="bi bi-check-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Pagamento Pendente"></i>
            {% endif %}
        </div>

        <hr class="col-12 d-lg-none">
        
        <div  class="col-12 col-lg-auto text-center text-lg-end">
            <a href="{% url 'projects:donation_detail' donation.id %}" class="text-decoration-none fw-bold">
                Mais detelhes
                <i class="bi bi-chevron-double-right text-primary"></i>
            </a> 
        </div>
    </div> 
</article>

projects/templates/projects/partials/donations_list.html
{% if donations %}
    <div class="d-grid gap-4">
        <ul class="list-group d-grid gap-4">
            {% for donation in donations %}
                <li class="list-group-item border-0 p-0">
                    {% include 'projects/partials/donation_preview.html' %}
                </li>
            {% endfor %}
        </ul>
        {% include 'global/partials/pagination.html' %}
    </div>
{% else %}
    <p>Nenhuma doação.</p>
{% endif %}

projects/templates/projects/partials/project_img_attrs.html
{% load static %}
{% if project.image %}
    src="{{ project.image.url }}"
{% else %}
    src="default-project-img.jpg"
{% endif %}
{% if project.image_description %}
    alt="{{ project.image_description }}" title="{{ project.image_description }}"
{% else %}
    alt='Imagem do projeto "{{ project.title }}"' title='Imagem do projeto "{{ project.title }}"'
{% endif %}

projects/templates/projects/partials/project_preview.html
<article class="card bg-light p-0 project-preview">
    <a href="{% url 'projects:project_detail' project.slug %}" class="text-decoration-none d-flex justify-content-start flex-column flex-lg-row">
        <section class="col-12 col-lg-4 p-0 border-end">
            <img class="project-img-preview" {% include 'projects/partials/project_img_attrs.html' %}>
        </section>
        <section class="col-12 col-lg-8 d-flex flex-column flex-fill">
            <header class="d-flex gap-0 gap-lg-4 flex-wrap align-items-baseline w-100 mx-auto py-4 py-lg-2 px-4 text-dark">
                <h3 class="flex-fill my-lg-2 my-0 text-center text-wrap text-break">
                    {{ project.title|truncatechars:32 }}
                </h3>
                {% if not project.is_published  %}
                    <hr class="w-100 d-lg-none">
                    <div class="flex-fill d-flex justify-content-evenly justify-content-lg-end my-lg-2">
                        <span class="fw-bold text-danger">
                            <i class="bi bi-clipboard-minus"></i>
                            Não publicado
                        </span>
                        {% if project.is_reproved %}
                            <span class="fw-bold text-danger">
                                <i class="bi bi-clipboard-x ms-3"></i>
                                Reprovado
                            </span>
                        {% else %}
                            <span class="fw-bold text-dark">
                                <i class="bi bi-clipboard-pulse ms-3"></i>
                                Em Análise
                            </span>
                        {% endif %}
                    </div>
                {% else %}
                    {% now "Y-m-d" as todays_date %}
                    {% if todays_date > project.deadline|date:"Y-m-d" %}
                        <hr class="w-100 d-lg-none">
                        <div class="col-12 col-lg-auto d-flex justify-content-evenly justify-content-lg-end">
                            <span class="fw-bold text-danger fw-bold text-danger">
                                <i class="bi bi-clipboard2-check"></i>
                                Encerrado
                            </span>
                        </div>
                    {% endif %}
                {% endif %}
            </header>
            <section class="card-body d-flex flex-column justify-content-center py-0 px-0">
                <div class="bg-info border d-flex flex-fill flex-column flex-lg-row justify-content-around align-items-start align-items-lg-center px-3 py-3 py-lg-4 text-body">
                    <div class="my-2 my-lg-0 d-flex align-items-center gap-2">
                        {% include 'users/partials/user_link.html' with user_link_user=project.owner user_link_icon_class='text-dark' user_link_separator='Criado por: ' user_link_separator_class='text-dark' user_link_username_class='text-reset' user_link_as_form=True %}
                    </div>
                    <div class="my-2 my-lg-0">
                        <strong class="text-dark">
                            <i class="bi bi-cash me-2"></i>
                            Objetivo:
                        </strong>
                        R$ {{ project.goal|floatformat:2 }}
                    </div>
                    <div class="my-2 my-lg-0">
                        <strong class="text-dark">
                            <i class="bi bi-cash-coin me-2"></i>
                            Valor Arrecadado:
                        </strong>
                        R$ {{ project.collected|floatformat:2 }}
                    </div>
                </div>
                <div class="p-3 preview-project-introduction text-body">
                    <div class="fw-bold mb-2 d-flex flex-nowrap">
                        <i class="bi bi-info-square me-2 text-primary"></i>
                        Introdução: 
                    </div>
                    <p class="card-text text-justify text-wrap text-break">{{ project.introduction }}</p>
                </div>
            </section>
            <section class="d-flex flex-wrap flex-fill justify-content-evenly justify-content-lg-between align-items-center m-0 px-4 py-3 py-lg-4 border-top text-muted">
                <span class="order-last order-lg-first text-center">Data de Encerramento: {{ project.deadline }}</span>
                
                <hr class="w-100 d-lg-none">

                <span class="order-first order-lg-last">
                    <i class="bi bi-chat-right-dots me-1"></i>
                    {{ project.topic_set.all|length }}
                    tópico{% if project.topic_set.all|length != 1%}s{% endif %}
                </span>
                
            </section>
        </section>
    </a>
</article>

projects/templates/projects/partials/projects_list.html
{% if projects %}
    <div class="d-grid gap-4">
        {% include 'global/partials/pagination.html' %}
        <ul class="list-group d-flex flex-wrap gap-4 overflow-hidden">
            {% for project in projects %}
                <li class="list-group-item border-0 p-0 col-12">
                    {% include 'projects/partials/project_preview.html' %}
                </li>
            {% endfor %}
        </ul>
        {% include 'global/partials/pagination.html' %}
    </div>
{% else %}
    <p>Nenhum projeto encontrado.</p>
{% endif %}

projects/templates/projects/partials/withdrawal_request_form_helper.html
<ul class="d-grid gap-3">
    <li>
        Insira as informações no seguinte formato: "<b>Campo: Valor</b>"
    </li>
    <li>
        Campos necessários:
        <ul class="list-group py-3">
            <li class="list-group-item">
                Para receber via transferência bancária:
                <ul class="my-2">
                    <li>Nome Completo</li>
                    <li>CPF ou CNPJ</li>
                    <li>Banco (Código)</li>
                    <li>Agência (Atenção: não coloque o dígito aqui)</li>
                    <li>Conta e dígito</li>
                    <li>Tipo de conta</li>
                </ul>
            </li>
            <li class="list-group-item">
                Para receber via PIX:
                <ul class="my-2">
                    <li>Nome Completo</li>
                    <li>Sua Chave PIX</li>
                </ul>
            </li>
        </ul>
    </li>  
    <li class="text-danger text-justify">
        <strong>Atenção: </strong>
        <span class="text-body">
            Verifique suas informações de contato informadas <a href="{% url 'users:user_update' %}#contact" target="_blank" rel="noopener noreferrer">aqui</a>. 
            Pois caso ocorra algum problema com a transferência, 
            nossa equipe entrará em contato através delas ou do e-mail cadastrado.
        </span>
    </li>
</ul>

projects/templates/projects/partials/withdrawal_request_preview.html
<article class="card m-0 project-preview">
    <div class="card-body px-3 m-0 d-flex flex-row justify-content-between flex-wrap  align-items-center">
        <div class="col-auto">
            <strong>
                <i class="bi bi-clipboard text-primary me-1"></i>
                Projeto: 
            </strong>
            <a href="{% url 'projects:project_detail' w_request.project.slug %}">
                {{ w_request.project.title|truncatechars:16 }}
            </a>
        </div>

        <hr class="col-12 d-lg-none">

        <div class="col-auto">
            <div class="d-flex  align-items-center">
                {% include 'users/partials/user_link.html' with user_link_user=w_request.user user_link_icon_class='text-primary' user_link_separator='Usuário: ' user_link_username_class='text-reset' %}
            </div>
        </div>

        <hr class="col-12 d-lg-none">

        <div class="col-auto">
            <strong>
                <i class="bi bi-calendar-event text-primary me-1"></i>
                Data:
            </strong> 
            {{ w_request.created|date:"SHORT_DATE_FORMAT" }}
        </div>

        <hr class="col-12 d-lg-none">

        <div class="col-auto text-start text-lg-end">
            <strong>
                <i class="bi bi-cash-coin text-primary me-1"></i>
                Valor:
            </strong> 
            R$ {{ w_request.project.collected|floatformat:2 }}
        </div>

        <div class="col-auto">
            {% if w_request.paid %}
                <i class="bi bi-check-circle-fill text-primary" data-bs-toggle="tooltip" data-bs-placement="right" title="Transferência Realizada"></i>
            {% else %}
                <i class="bi bi-check-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Transferência Pendente"></i>
            {% endif %}
        </div>

        <hr class="col-12 d-lg-none">
        
        <div  class="col-12 col-lg-auto text-center text-lg-end">
            <a href="{% url 'projects:withdrawal_request_detail' w_request.id %}" class="text-decoration-none fw-bold">
                Mais detelhes
                <i class="bi bi-chevron-double-right text-primary"></i>
            </a> 
        </div>
    </div> 
</article>

projects/templates/projects/partials/withdrawal_requests_list.html
{% if w_requests %}
    <div class="d-grid gap-4">
        <ul class="list-group d-grid gap-4">
            {% for w_request in w_requests %}
                <li class="list-group-item border-0 p-0">
                    {% include 'projects/partials/withdrawal_request_preview.html' %}
                </li>
            {% endfor %}
        </ul>
        {% include 'global/partials/pagination.html' %}
    </div>
{% else %}
    <p>Nenhuma solicitação de saque.</p>
{% endif %}