superacao_coletiva/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # Django Admin
    path("admin/", admin.site.urls),
    # User Management
    path("accounts/", include("allauth.urls")),
    # Home
    path("", TemplateView.as_view(
        template_name="global/pages/home.html"), name='home'),
    # Users
    path("users/", include("users.urls")),
    # Projects
    path("projects/", include("projects.urls")),
    # Topics
    path("topics/", include("topics.urls")),

    # 3rd party

    # TinyMCE
    path('tinymce/', include('tinymce.urls')),
    # PWA
    path('', include('pwa.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

topics/urls.py
from django.urls import path

from topics import views

app_name = "topics"

urlpatterns = [
    path("create-topic/",
         views.TopicCreateView.as_view(), name="topic_create"),
    path("delete-topic/<int:pk>/",
         views.TopicDeleteView.as_view(), name="topic_delete"),
    path("<int:pk_topic>/",
         views.TopicView.as_view(), name="topic_detail"),

    path("create-message/",
         views.MessageCreateView.as_view(), name="message_create"),

    path("vote/",
         views.VoteMessageView.as_view(), name="vote_message"),
]

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("update/",
         views.UserChange.as_view(), name="user_update"),
    path("profile/<int:pk>/",
         views.UserProfileView.as_view(), name="user_profile"),
]

topics/models.py
from django.conf import settings
from django.db import models
from model_utils.models import TimeStampedModel

from projects.models import Project


class Topic(TimeStampedModel, models.Model):
    user = models.ForeignKey(
        verbose_name="Criador",
        to=settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )
    project = models.ForeignKey(
        verbose_name="Projeto",
        to=Project,
        on_delete=models.SET_NULL,
        null=True

    )

    title = models.CharField(verbose_name="Título", max_length=255)
    description = models.TextField(verbose_name="Descrição")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Tópico"
        verbose_name_plural = "Tópicos"


class Message(TimeStampedModel, models.Model):
    user = models.ForeignKey(
        verbose_name="Criador",
        to=settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )
    topic = models.ForeignKey(
        verbose_name="Tópico",
        to=Topic,
        on_delete=models.CASCADE
    )

    content = models.TextField(verbose_name="Conteúdo")

    def __str__(self):
        return (self.content[:75] + '...') if len(self.content) > 75 else self.content

    class Meta:
        verbose_name = "Mensagem"
        verbose_name_plural = "Mensagens"


class MessageVote(TimeStampedModel, models.Model):
    user = models.ForeignKey(
        verbose_name="Usuário",
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    message = models.ForeignKey(
        verbose_name="Mensagem",
        to=Message,
        on_delete=models.CASCADE
    )

    value = models.BooleanField(
        verbose_name="Gostou", default=True)

    class Meta:
        verbose_name = "Voto Mensagem"
        verbose_name_plural = "Votos Mensagens"

topics/forms.py
from crispy_forms.helper import FormHelper
from django import forms

from topics.models import Message, Topic


class TopicCreateForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['user', 'project', 'title', 'description']

        widgets = {
            'user': forms.HiddenInput(),
            'project': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False


class MessageCreateForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['user', 'topic', 'content']

        widgets = {
            'user': forms.HiddenInput(),
            'topic': forms.HiddenInput(),
            'content': forms.Textarea(attrs={
                'class': "form-control auto-height-textarea shadow-sm",
                'placeholder': "Escreva uma resposta para o tópico",
                'rows': "3",
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_labels = False
        self.helper.wrapper_class = 'flex-fill me-lg-3'

topics/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import BadRequest
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, View
from django_filters.views import FilterView

from topics.filters import MessageOrderByFilter
from topics.forms import MessageCreateForm, TopicCreateForm
from topics.models import Message, MessageVote, Topic

MESSAGES_PAGINATE_BY = 5


@method_decorator(login_required, name='dispatch')
class TopicCreateView(CreateView):
    model = Topic
    form_class = TopicCreateForm

    def get_success_url(self) -> str:
        return reverse("topics:topic_detail", kwargs={'pk_topic': self.object.id})

    def get(self, request):
        raise Http404

    def form_valid(self, form):
        if form.cleaned_data.get('user') != self.request.user:
            raise BadRequest('Invalid request.')

        return super().form_valid(form)

    def form_invalid(self, form):
        self.request.session['form'] = self.request.POST
        return redirect(reverse("projects:project_detail", kwargs={'slug': form.cleaned_data['project'].slug}))


@method_decorator(login_required, name='dispatch')
class TopicDeleteView(UserPassesTestMixin, DeleteView):
    model = Topic
    template_name = 'topics/pages/topic_delete.html'

    def test_func(self):
        return (
            self.request.user.is_staff or
            self.request.user == self.get_object().user or
            self.request.user == self.get_object().project.owner
        )

    def get_success_url(self) -> str:
        return reverse("projects:project_detail", kwargs={'slug': self.get_object().project.slug})


class TopicView(FilterView):
    model = Message
    context_object_name = 'msgs'
    ordering = ['-created']
    template_name = 'topics/pages/topic.html'
    paginate_by = MESSAGES_PAGINATE_BY
    filterset_class = MessageOrderByFilter

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)

        qs = qs.filter(
            topic__pk=self.kwargs['pk_topic'],
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx['topic'] = get_object_or_404(
            Topic,
            pk=self.kwargs['pk_topic'],
        )

        for message in ctx['msgs']:
            message.upvotes = message.messagevote_set.filter(
                value=True).count()
            message.downvotes = message.messagevote_set.filter(
                value=False).count()

            if self.request.user.is_authenticated:
                try:
                    message.vote = message.messagevote_set.get(
                        user=self.request.user)
                except:
                    pass

        form_data = self.request.session.get('message_form')
        if form_data is not None:
            ctx['message_form'] = MessageCreateForm(form_data)
            del self.request.session['message_form']
        else:
            ctx['message_form'] = MessageCreateForm(
                initial={
                    'user': self.request.user,
                    'topic': ctx['topic'],
                })

        return ctx


@method_decorator(login_required, name='dispatch')
class MessageCreateView(CreateView):
    model = Message
    form_class = MessageCreateForm

    def get_success_url(self) -> str:
        return reverse("topics:topic_detail", kwargs={'pk_topic': self.object.topic.id})

    def get(self, request):
        raise Http404

    def form_valid(self, form):
        if form.cleaned_data.get('user') != self.request.user:
            raise BadRequest('Invalid request.')

        return super().form_valid(form)

    def form_invalid(self, form):
        self.request.session['message_form'] = self.request.POST
        return redirect(reverse("topics:topic_detail", kwargs={'pk_topic': form.cleaned_data['topic'].id}))


@method_decorator(login_required, name='dispatch')
class VoteMessageView(UserPassesTestMixin, View):

    def test_func(self):
        message_id = self.request.POST['message']
        user = self.request.POST['user']

        try:
            Message.objects.get(pk=message_id)
        except:
            return False

        return str(self.request.user.id) == user

    def post(self, request, *args, **kwargs):
        message_id = self.request.POST['message']
        value = request.POST['value']

        message = Message.objects.get(pk=message_id)

        vote = None
        try:
            vote = MessageVote.objects.get(
                user=self.request.user,
                message=message,
            )
        except:
            vote = MessageVote()
            vote.user = self.request.user
            vote.message = message
            vote.value = None

        if value == "True":
            if vote.value == True:
                vote.delete()
            else:
                vote.value = True
                vote.save()

        elif value == "False":
            if vote.value == False:
                vote.delete()
            else:
                vote.value = False
                vote.save()

        next_url = request.POST.get(
            'next',
            reverse('topics:topic_detail', kwargs={
                'pk_topic': message.topic.id,
            })
        )

        return HttpResponseRedirect(next_url)

topics/templates/topics/partials/message.html
<article id="message-{{ message.id }}" class="d-flex flex-column flex-lg-row">
    <div class="card border-0 bg-light p-0 shadow-sm col">
        <div class="card-header d-flex justify-content-between gap-3 flex-wrap align-items-baseline
        {% if user == message.user %}
            bg-secondary text-white    
        {% endif %}
        ">

            {% include 'users/partials/user_link.html' with user_link_user=message.user user_link_username_class='text-reset mb-2' %}

            <span class="text-lowercase fs-small
            {% if user != message.user %}
                text-black-50
            {% endif %}
            ">
                {{ message.created }}
            </span>
        </div>
        <div class="card-body">
            {{ message.content|linebreaks }}
        </div>
    </div>
    <div class="d-flex flex-row flex-lg-column gap-3 justify-content-end justify-content-lg-start col-auto ps-0 ps-lg-3 pt-3 pt-lg-0">
        <form action="{% url 'topics:vote_message' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="message" value="{{ message.id }}">
            <input type="hidden" name="user" value="{{ user.id }}">
            <input type="hidden" name="next" value="{{ request.path }}{% if request.GET.urlencode %}?{{ request.GET.urlencode }}{% endif %}#message-{{ message.id }}">
            <input type="hidden" name="value" value="True">
            {% if message.vote.value == True %}
                <button type="submit" class="border-0 bg-transparent text-muted" data-bs-toggle="tooltip" data-bs-placement="right" title='Remover "Gostei"'>
                    <i class="bi bi-hand-thumbs-up-fill text-primary"></i>
            {% else %}
                <button type="submit" class="border-0 bg-transparent text-muted" data-bs-toggle="tooltip" data-bs-placement="right" title='Marcar como "Gostei"'>
                    <i class="bi bi-hand-thumbs-up"></i>
            {% endif %}
            {{ message.upvotes }}
            </button>
        </form>
        <form action="{% url 'topics:vote_message' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="message" value="{{ message.id }}">
            <input type="hidden" name="user" value="{{ user.id }}">
            <input type="hidden" name="next" value="{{ request.path }}{% if request.GET.urlencode %}?{{ request.GET.urlencode }}{% endif %}#message-{{ message.id }}">
            <input type="hidden" name="value" value="False">
            {% if message.vote.value == False %}
                <button type="submit" href="" class="border-0 bg-transparent text-muted" data-bs-toggle="tooltip" data-bs-placement="right" title='Remover "Não Gostei"'>
                    <i class="bi bi-hand-thumbs-down-fill text-primary"></i>
            {% else %}
                <button type="submit" href="" class="border-0 bg-transparent text-muted" data-bs-toggle="tooltip" data-bs-placement="right" title='Marcar como "Não Gostei"'>
                    <i class="bi bi-hand-thumbs-down"></i>
            {% endif %}
            {{ message.downvotes }}
            </button>
        </form>
    </div>
</article>

topics/templates/topics/partials/messages_list.html
{% if msgs %}
    <div class="d-grid gap-4">
        <ul class="list-group d-grid gap-4">
            {% for message in msgs %}
                <li class="list-group-item border-0 p-0">
                    {% include 'topics/partials/message.html' %}
                </li>
            {% endfor %}
        </ul>
        {% include 'global/partials/pagination.html' %}
    </div>
{% else %}
    <p>Nenhum resposta publicada. Seja o primeiro a responder este tópico!</p>
{% endif %}

topics/templates/topics/partials/topic_preview.html
{% load static %}

<article class="card w-100">
    <a href="{% url 'topics:topic_detail' topic.id %}" class="text-decoration-none">
        <div class="card-header py-4 py-lg-2 d-flex flex-column flex-lg-row flex-wrap justify-content-between align-items-start align-items-lg-center bg-info">
            <h5 class="card-title text-dark">
                <i class="bi bi-chat-right-dots text-primary fs-5 me-1"></i>
                {{topic.title}}
                <small class="text-muted fw-light">
                    {% if topic.message_set.all|length == 1%}
                        ({{topic.message_set.all|length}} mensagem)
                    {% else %}
                        ({{topic.message_set.all|length}} mensagens)
                    {% endif %}
                </small>
            </h5>
            <hr class="col-12 d-lg-none">
            <span class="d-flex flex-column flex-lg-row justify-content-end">
                <div class="d-flex gap-2 align-items-center">
                    {% include 'users/partials/user_link.html' with user_link_user=topic.user user_link_icon_class='text-primary' user_link_separator='Criado por: ' user_link_separator_class='text-primary' user_link_username_class='text-black' user_link_as_form=True %}
                </div>
                {% if user == topic.user or user == project.owner %}
                    <form class="d-none d-lg-inline ms-4" action="{% url 'topics:topic_delete' topic.id %}" method="get">
                        <button type="submit" class="btn btn-sm btn-danger"> 
                            <i class="bi bi-x-lg"></i>
                            Excluir
                        </button>
                    </form>
                {% endif %}
            </span>
        </div>
        <div class="card-body text-body">
            <p class="card-text text-justify">
                <span class="fw-bold">
                    Decrição: 
                </span>
                <div class="text-break text-wrap">
                    {{topic.description|linebreaks|truncatechars:256}}
                </div>
            </p>
        </div>
    </a>
    <div class="card-footer d-lg-none p-0">
        {% if user == topic.user and project %}
            <a href="{% url 'topics:topic_delete' topic.id %}">
                <button class="btn btn-sm btn-danger rounded-0 rounded-bottom w-100">
                    <i class="bi bi-x-lg me-1"></i>
                    Excluir
                </button>
            </a>
        {% endif %}
    </div>
</article>

topics/templates/topics/partials/topics_list.html
{% if topics %}
    <div class="d-grid gap-4">
        <ul class="list-group d-grid gap-4">
            {% for topic in topics %}
                <li class="list-group-item border-0 p-0">
                    {% include 'topics/partials/topic_preview.html' %}
                </li>
            {% endfor %}
        </ul>
        {% include 'global/partials/pagination.html' %}
    </div>
{% else %}
    <p>Nenhum tópico cadastrado.</p>
{% endif %}